---
title: "Homework_04"
output: html_document
date: "2022-11-01"
---

```{r}
library(sf)
library(tmap)
library(here)
library(dplyr)
library(janitor)
library(tidyverse)
library(classInt)
library(geojsonio)
library(ggplot2)
library(maptools)
library(pacman)
library(OpenStreetMap)
library(plotly)
library(RColorBrewer)
library(RSQLite)
library(rgeos)
library(rgdal)
library(sp)
library(shiny)
library(shinyjs)
library(tmaptools)

```


```{r}
install.packages("countrycode")
library(countrycode)
```

# Read in the gender inequality data
```{r}
GenderIne<- read.csv(here::here("prac4_Data","HDR21-22_Composite_indices_complete_time_series.csv")) %>%
  clean_names()
```

# Reand in world countries shapfile
```{r}
WorldData <- st_read(here("prac4_Data","World_Countries_(Generalized).geojson"))
```

# Select necessary data
```{r}
GIgii <- GenderIne %>% 
  dplyr::select(c(iso3,country,gii_2010,gii_2019))

GIgii

```

# Make a new colum 
```{r}
GIgii1019 <- GIgii %>%
  mutate(diff=gii_2019-gii_2010)

GIgii1019
```

# Join GIgii1019 to WorldData
```{r}
WorldData02 <- WorldData %>%
  clean_names() %>%
  left_join(.,
            GIgii1019,
            by = c("country" = "country"))

WorldData02
```

# Map
```{r}
tmap_mode("plot")

tm_shape(WorldData02)+
tm_polygons("diff", 
              style="jenks",
              palette="Blues",
              midpoint=NA,
              title="Change in index",
              alpha = 0.5) + 
  tm_compass(position = c("left", "bottom"),type = "arrow") + 
  tm_scale_bar(position = c("left", "bottom")) +
  tm_layout(title = "Difference in gender inequality between 2010 and 2019", legend.position = c("right", "bottom"))
```

