---
title: "wk5_spatial join_advanced map"
output: html_document
date: "2022-11-15"
---

# Spatial Join
# 将数据集连接在一起并保留它们的所有属性数据
```{r}
# 读取伦敦自治区shp数据
library(sf)

Londonborough <- st_read(here::here("prac5_Data",
                                    "statistical-gis-boundaries-london",
                                    "ESRI",
                                    "London_Borough_Excluding_MHW.shp"))%>%
  st_transform(., 27700)

```

```{r}
# 读取OSM数据
OSM <- st_read(here::here("prac5_Data",
                          "greater-london-latest-free.shp", 
                          "gis_osm_pois_a_free_1.shp")) %>%
  st_transform(., 27700) %>%
  #select hotels only
  dplyr::filter(fclass == 'hotel')

```

```{r}
# 保留酒店数据的属性，但还会附加自治市镇的属性
# st_join()默认为左连接
# 意味着：Londonborough是左数据集，并且所有右数据OSM都已附加到它
join_example <- st_join(Londonborough, OSM)

head(join_example)

```


# 【静态地图】
# 标准化（normalise）伦敦的Hotel Airbnb数据
# 1.读取数据
# OSM
```{r}

library(sf)
library(tmap)
library(tmaptools)
library(tidyverse)
library(here)

OSM <- st_read(here::here("prac5_Data",
                          "greater-london-latest-free.shp", 
                          "gis_osm_pois_a_free_1.shp")) %>%
  st_transform(., 27700) %>%
  #select hotels only
  dplyr::filter(fclass == 'hotel')

```

# 世界城市
```{r}
Worldcities <- st_read(here::here("prac5_Data",
                                  "World_Cities",
                                  "World_Cities.shp")) %>%
  st_transform(., 27700)

```

# UK外轮廓
```{r}
UK_outline <- st_read(here::here("prac5_Data", 
                                 "gadm41_GBR_shp", 
                                 "gadm41_GBR_0.shp")) %>%
  st_transform(., 27700)

```

# 伦敦自治区
```{r}
Londonborough <- st_read(here::here("prac5_Data",
                                    "statistical-gis-boundaries-london",
                                    "ESRI",
                                    "London_Borough_Excluding_MHW.shp"))%>%
  st_transform(., 27700)

```

# 2.只保留London范围内的Hotel Airbnb，并计算各数量
```{r}

# 读取Airbnb的csv数据，将其转化为空间数据
Airbnb <- read_csv("prac5_Data/listings.csv") %>%
  st_as_sf(., coords = c("longitude", "latitude"), 
                   crs = 4326) %>%
    st_transform(., 27700)%>%
  
    # 选择全年开放的地方
    filter(room_type == 'Entire home/apt' & availability_365 =='365')


# 为数据的连接创建function
# 替换 data1 data2为自己需要的数据
# 没搞懂❓
Joinfun <- function(data1, data2){

output<- data1%>%
  st_join(data2,.) %>%
  add_count(GSS_CODE, name="hotels_in_borough") 

  return(output)
}


# 选择位于伦敦自治区的Hotel
Hotels <- Joinfun(OSM, Londonborough)

# 选择位于伦敦自治区的Airbnb
Airbnb <- Joinfun(Airbnb, Londonborough)
 

# 在整个worldcities的范围内，挑选B L E
# 并命名United Kingdom
Worldcities2 <- Worldcities %>%
  filter(CNTRY_NAME=='United Kingdom'&
           Worldcities$CITY_NAME=='Birmingham'|
           Worldcities$CITY_NAME=='London'|
           Worldcities$CITY_NAME=='Edinburgh')

newbb <- c(xmin=-296000, ymin=5408, xmax=655696, ymax=1000000)
  
UK_outlinecrop <- UK_outline$geometry %>%
  st_crop(., newbb)


# 计算伦敦每个自治区Hotel Airbnb数量
Hotels <- Hotels %>%
  group_by(., GSS_CODE, NAME)%>%
  summarise(`Accomodation count` = unique(hotels_in_borough))

Airbnb <- Airbnb %>%
  group_by(., GSS_CODE, NAME)%>%
  summarise(`Accomodation count` = unique(hotels_in_borough))

```

# 3.制作地图
```{r}

tmap_mode("plot")

# 设定分类区间
breaks = c(0, 5, 12, 26, 57, 286) 

# 制作Hotel的标准化地图
tm1 <- tm_shape(Hotels) + 
  tm_polygons("Accomodation count", 
              breaks=breaks,
              palette="PuBu")+
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(a)", position=c(0,0.85), size=1.5)

# 制作Airbnb的标准化地图
tm2 <- tm_shape(Airbnb) + 
  tm_polygons("Accomodation count",
              breaks=breaks, 
              palette="PuBu") + 
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(b)", position=c(0,0.85), size=1.5)

# 制作伦敦大轮廓，并高亮B L E
tm3 <- tm_shape(UK_outlinecrop)+ 
  tm_polygons(col="darkslategray1")+
  tm_layout(frame=FALSE)+
  tm_shape(Worldcities2) +
  tm_symbols(col = "red", scale = .5)+
  tm_text("CITY_NAME", xmod=-1, ymod=-0.5)

# 制作详细信息
# alpha透明度, compass指南针, scale比例，legend图例
# style数据划分不同颜色，palette配色方案
legend <- tm_shape(Hotels) +
    tm_polygons("Accomodation count",
                palette="PuBu") +
    tm_scale_bar(position=c(0.2,0.04), text.size=0.6)+
    tm_compass(north=0, position=c(0.65,0.6))+
    tm_layout(legend.only = TRUE, legend.position=c(0.2,0.25),asp=0.1)+
    tm_credits("(c) OpenStreetMap contrbutors and Air b n b", position=c(0.0,0.0))
  
t=tmap_arrange(tm1, tm2, tm3, legend, ncol=2)

t
```

# 4.1 使用网格整齐的排版
```{r}
library(grid)
grid.newpage()

pushViewport(viewport(layout=grid.layout(2,2)))
print(tm1, vp=viewport(layout.pos.col=1, layout.pos.row=1, height=5))
print(tm2, vp=viewport(layout.pos.col=2, layout.pos.row=1, height=5))
print(tm3, vp=viewport(layout.pos.col=1, layout.pos.row=2, height=5))
print(legend, vp=viewport(layout.pos.col=2, layout.pos.row=2, height=5))
```

# 4.2 设计感排版
```{r}
# 以Airbnb的图为主
Londonbb <- st_bbox(Airbnb,
                    crs = st_crs(Airbnb))%>%

  st_as_sfc()

```

```{r}
# 设置布局、大小
# alpha透明度, compass指南针, scale比例，legend图例
# style数据划分不同颜色，palette配色方案

main <- tm_shape(Airbnb, bbbox = Londonbb) + 
  tm_polygons("Accomodation count",
              breaks=breaks, 
              palette="PuBu")+
  tm_scale_bar(position = c("left", "bottom"), text.size = .75)+
  tm_layout(legend.position = c("right","top"), 
            legend.text.size=.75, 
            legend.title.size = 1.1,
            frame=FALSE)+
  tm_credits("(c) OpenStreetMap contrbutors and Air b n b", position=c(0.0,0.0))+

  tm_compass(type = "8star", position = c(0.06, 0.1)) +

  #bottom left top right
  tm_layout(inner.margin=c(0.02,0.02,0.02,0.2))
```

```{r}
# 具体设计UK小图形式
inset = tm_shape(UK_outlinecrop) + tm_polygons() +
  tm_shape(Londonbb)+ 
  tm_borders(col = "grey40", lwd = 3)+
    tm_layout(frame=FALSE,
            bg.color = "transparent")+
  tm_shape(Worldcities2) +
  tm_symbols(col = "red", scale = .5)+
  tm_text("CITY_NAME", xmod=-1.5, ymod=-0.5)
```

```{r}
# UK轮廓小图位置
library(grid)
main
print(inset, vp = viewport(0.86, 0.29, width = 0.5, height = 0.55))
```
# 5.导出地图
```{r}
tmap_save(t, 'hotelsandairbnbR.png')

library(grid)
tmap_save(main,insets_tm = inset,insets_vp=viewport(x=0.86, y=0.29, width=.5, height=.55), filename="test.pdf", dpi=600)

```


# 【基本交互地图】
```{r}
tmap_mode("view")

tm_shape(Airbnb) + 
  tm_polygons("Accomodation count", breaks=breaks) 

```


# 【高级交互地图】
```{r}

library(leafpop)
library(leaflet)

#join data
Joined <- Airbnb%>%
  st_join(., Hotels, join = st_equals)%>%
  dplyr::select(GSS_CODE.x, NAME.x, `Accomodation count.x`, `Accomodation count.y`)%>%
  dplyr::rename(`GSS code` =`GSS_CODE.x`,
                `Borough` = `NAME.x`,
                `Airbnb count` = `Accomodation count.x`,
                `Hotel count`= `Accomodation count.y`)%>%
  st_transform(., 4326)
  
  
#remove the geometry for our pop up boxes to avoid
popupairbnb <-Joined %>%
  st_drop_geometry()%>%
  dplyr::select(`Airbnb count`, Borough)%>%
  popupTable()

popuphotel <-Joined %>%
  st_drop_geometry()%>%
  dplyr::select(`Hotel count`, Borough)%>%
  popupTable()

tmap_mode("view")

# set the colour palettes using our previously defined breaks


pal1 <- Joined %>%
  colorBin(palette = "YlOrRd", domain=.$`Airbnb count`, bins=breaks)

pal1 <-colorBin(palette = "YlOrRd", domain=Joined$`Airbnb count`, bins=breaks)

pal2 <- Joined %>%
  colorBin(palette = "YlOrRd", domain=.$`Hotel count`, bins=breaks)


map<- leaflet(Joined) %>%
  # add basemap options
  addTiles(group = "OSM (default)") %>%
  addProviderTiles(providers$Stamen.Toner, group = "Toner") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
  addProviderTiles(providers$CartoDB.Positron, group = "CartoDB")%>%
  
  #add our polygons, linking to the tables we just made
  addPolygons(color="white", 
              weight = 2,
              opacity = 1,
              dashArray = "3",
              popup = popupairbnb,
              fillOpacity = 0.7,
              fillColor = ~pal2(`Airbnb count`),
              group = "Airbnb")%>%
  
  addPolygons(fillColor = ~pal2(`Hotel count`), 
              weight = 2,
              opacity = 1,
              color = "white",
              dashArray = "3",
              popup = popupairbnb,
              fillOpacity = 0.7,group = "Hotels")%>%
  # add a legend
  addLegend(pal = pal2, values = ~`Hotel count`, group = c("Airbnb","Hotel"), 
            position ="bottomleft", title = "Accomodation count") %>%
  # specify layers control
  addLayersControl(
    baseGroups = c("OSM (default)", "Toner", "Toner Lite", "CartoDB"),
    overlayGroups = c("Airbnb", "Hotels"),
    options = layersControlOptions(collapsed = FALSE)
  )

# plot the map
map

```



